
name: sem-var

on:
 push:
  branches:
    - master
    - rc
    - dev
    - rc-fix
    
    
jobs:

 job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
         persist-credentials: false
  
      - uses: actions/setup-node@v3
        with:
         node-version: 18.x
      - name: setup semantic-release
        run: npm install -g semantic-release @semantic-release/git @semantic-release/changelog -D
      - name: release
        env:
         GITHUB_TOKEN: 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
        run: npx semantic-release
